---
- name: create checkouts dir
  file: path=/checkouts state=directory owner=vagrant group=vagrant mode=0775

- name: clone
  git: repo=git.assembla.com/jh.communit.git
       dest=/checkouts/community
       accept_hostkey=True
       update=no
       version=develop
  sudo: true
  sudo_user: "vagrant"

- name: git | turn off filemode
  command: git config core.fileMode false
  args:
    chdir: /checkouts/{{ item }}
  with_items:
    - community
