---
- name: git | add .gitconfig files
  template: src=git/gitconfig.j2 dest=/home/vagrant/.gitconfig owner=vagrant group=vagrant mode=0644

- name: create checkouts dir
  file: path=/checkouts state=directory owner=vagrant group=vagrant mode=0775

- name: git | clone codebase
  git: repo=git@github.com:HitomiKojiru/Community.git
       dest=/checkouts/community
       accept_hostkey=True
       update=no
       version=develop
  sudo: true
  sudo_user: "vagrant"

- name: git | turn off filemode
  command: git config core.fileMode false
  args:
    chdir: /checkouts/{{ item }}
  with_items:
    - community
